export const recipes = [
  {
    name: "Chicken Fried Rice",
    servings: 2,
    instructions: [
      "Dice chicken and season with salt and pepper.",
      "Heat oil in a large skillet or wok. Add chicken and cook through.",
      "Add diced onion and garlic, cook until softened.",
      "Push everything to one side, scramble the eggs on the other side of the pan.",
      "Mix in peas, rice, and soy sauce. Stir-fry for a few minutes until heated through.",
      "Adjust seasoning and serve hot.",
    ],
    ingredients: [
      {
        name: "Chicken breast",
        quantity: 200,
        unit: "g",
        macros_per_unit: {
          calories: 1.65,
          protein: 0.31,
          fat: 0.04,
          carbs: 0,
        },
      },
      {
        name: "Cooked white rice",
        quantity: 250,
        unit: "g",
        macros_per_unit: {
          calories: 1.3,
          protein: 0.028,
          fat: 0.003,
          carbs: 0.28,
        },
      },
      {
        name: "Eggs",
        quantity: 100,
        unit: "g",
        macros_per_unit: {
          calories: 1.43,
          protein: 0.125,
          fat: 0.1,
          carbs: 0.01,
        },
      },
    ],
  },
  {
    name: "Beef Curry with White Rice",
    servings: 2,
    ingredients: [
      {
        name: "Lean Beef (cubed)",
        quantity: 250,
        unit: "grams",
        macros_per_unit: { calories: 2.1, protein: 0.3, fat: 0.08, carbs: 0 },
      },
      {
        name: "Onion (chopped)",
        quantity: 100,
        unit: "grams",
        macros_per_unit: { calories: 0.4, protein: 0.01, fat: 0, carbs: 0.09 },
      },
      {
        name: "Tomato (chopped)",
        quantity: 80,
        unit: "grams",
        macros_per_unit: {
          calories: 0.18,
          protein: 0.009,
          fat: 0,
          carbs: 0.04,
        },
      },
      {
        name: "Curry Leaves",
        quantity: 5,
        unit: "grams",
        macros_per_unit: {
          calories: 2.5,
          protein: 0.03,
          fat: 0.06,
          carbs: 0.02,
        },
      },
      {
        name: "Ginger (grated)",
        quantity: 10,
        unit: "grams",
        macros_per_unit: { calories: 0.8, protein: 0.017, fat: 0, carbs: 0.18 },
      },
      {
        name: "Garlic (minced)",
        quantity: 10,
        unit: "grams",
        macros_per_unit: { calories: 1.49, protein: 0.06, fat: 0, carbs: 0.33 },
      },
      {
        name: "Spices (turmeric, chili powder, coriander powder)",
        quantity: 10,
        unit: "grams",
        macros_per_unit: { calories: 3.0, protein: 0.1, fat: 0.05, carbs: 0.6 },
      },
      {
        name: "Coconut Milk (light)",
        quantity: 100,
        unit: "ml",
        macros_per_unit: {
          calories: 1.8,
          protein: 0.02,
          fat: 0.18,
          carbs: 0.02,
        },
      },
      {
        name: "White Rice (cooked)",
        quantity: 150,
        unit: "grams",
        macros_per_unit: {
          calories: 1.3,
          protein: 0.028,
          fat: 0.003,
          carbs: 0.28,
        },
      },
    ],
    instructions: [
      "Heat a pan and sauté onions, garlic, and ginger until fragrant.",
      "Add spices and cook for a minute.",
      "Add beef cubes and brown on all sides.",
      "Add tomatoes and curry leaves, cook until soft.",
      "Pour in light coconut milk and simmer on low heat for 30-40 minutes until beef is tender.",
      "Serve hot with cooked white rice.",
    ],
  },
  {
    name: "Chicken Curry with White Rice",
    servings: 2,
    instructions: [
      "Dice chicken thighs and season lightly.",
      "Heat oil in a pan, sauté onions, garlic, ginger, and curry leaves until fragrant.",
      "Add tomatoes and spices, cook until soft.",
      "Add chicken and cook until done.",
      "Pour in light coconut milk, simmer for 10 minutes.",
      "Serve with cooked white rice.",
    ],
    ingredients: [
      {
        name: "Chicken thigh (boneless, skinless)",
        quantity: 300,
        unit: "g",
        macros_per_unit: {
          calories: 1.76,
          protein: 0.27,
          fat: 0.11,
          carbs: 0,
        },
      },
      {
        name: "Light coconut milk",
        quantity: 100,
        unit: "g",
        macros_per_unit: {
          calories: 0.86,
          protein: 0.006,
          fat: 0.08,
          carbs: 0.01,
        },
      },
      {
        name: "Onion",
        quantity: 100,
        unit: "g",
        macros_per_unit: {
          calories: 0.4,
          protein: 0.01,
          fat: 0.002,
          carbs: 0.09,
        },
      },
      {
        name: "Tomato",
        quantity: 100,
        unit: "g",
        macros_per_unit: {
          calories: 0.18,
          protein: 0.009,
          fat: 0.002,
          carbs: 0.04,
        },
      },
      {
        name: "Garlic",
        quantity: 10,
        unit: "g",
        macros_per_unit: {
          calories: 1.5,
          protein: 0.06,
          fat: 0.005,
          carbs: 0.33,
        },
      },
      {
        name: "Ginger",
        quantity: 10,
        unit: "g",
        macros_per_unit: {
          calories: 0.8,
          protein: 0.02,
          fat: 0.01,
          carbs: 0.18,
        },
      },
      {
        name: "Curry leaves",
        quantity: 2,
        unit: "g",
        macros_per_unit: {
          calories: 0.6,
          protein: 0.05,
          fat: 0.01,
          carbs: 0.09,
        },
      },
      {
        name: "Oil",
        quantity: 10,
        unit: "g",
        macros_per_unit: {
          calories: 9,
          protein: 0,
          fat: 1,
          carbs: 0,
        },
      },
      {
        name: "Cooked white rice",
        quantity: 200,
        unit: "g",
        macros_per_unit: {
          calories: 1.3,
          protein: 0.028,
          fat: 0.003,
          carbs: 0.28,
        },
      },
    ],
  },
];
